print("Sales Analyitcs Project")
print("This is my first git project")
print("Data analytics started")
print("Working on feature analysis")
print("Sales analysis feature development")
print("Monthly sales performance analysis started")